-- Thêm nguyên liệu vào bảng ingredients
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'hành lá');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'tỏi');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'ớt');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'gia vị');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'nước mắm');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'đường');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'muối');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'ớt bột');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'bột ngọt');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'bún');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'gạo');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'mỡ');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'dầu ăn');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'bắp cải');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'cà chua');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'bí đỏ');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'cà rốt');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'nấm');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau cải');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau muống');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau mùi');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau xà lách');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau bina');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau cải thảo');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau răm');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau ngổ');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau cần tàu');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau diếp');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau mùng');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau dền');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau đay');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau húng');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau dền đỏ');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau dền trắng');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau cải bó xôi');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau xôi');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau mùi tàu');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau cải xoăn');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau dền mảy');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau dền lá đỏ');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau dền lá xanh');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau bina nhỏ');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau bina lớn');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau dền mảnh');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau dền bào');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau dền tươi');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau mùng bìa');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau mùng tươi');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'rau mùng ống');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'tinh bột nghệ');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'tinh bột sắn dây');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'mì sợi');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'bột hạt nêm');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'dầu ăn ăn mì');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'gạo nếp');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'sốt cà chua');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'sốt ớt');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'đậu phụ');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'bánh tráng');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'bánh mì');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'bột gạo');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'bột mì');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'bột bắp');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'bột nếp');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'bún đậu');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'mì xào');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'đậu hủ');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'mỳ ý');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'mỳ gói');
INSERT INTO ingredients (ingredientID, ingredientName) VALUES (NULL, 'mỳ trứng');
------------------------------------------------------------------------------------
-- Thêm loại món ăn vào bảng typeDisks
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'món Hàn');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'món Việt');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'món Trung');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'món Nhật');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'món Ý');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'món Pháp');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'món Thái');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'món Ấn');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'siêu cay');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'ăn kiêng');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'ăn chay');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'lạnh');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'nước dùng');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'hấp');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'nướng');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'xào');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'luộc');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'món nhanh');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'tráng miệng');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'khai vị');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'chính');
INSERT INTO typeDisks (typeID, typeName) VALUES (NULL, 'ăn nhẹ');

